name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      MNEMONIC: ${{ secrets.WALLET_MNEMONIC }}
      FUNDS_COLLECTOR: ${{ secrets.FUNDS_COLLECTOR_WALLET }}

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: |
          npm install
          touch .env.local
      - run: npm run test
      - uses: actions/upload-artifact@v2  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: test-results
          path: '*.xml'
          reporter: mocha-json
